package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAlumno.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IAlumno {
	public String getNumero_Matricula();
}
