package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAula.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IAula {
	public String getId();
	
	public String getCentro();
	
	public int getNumeroCentro();
	
	public int getAforo();
	public String getTipo();
	
	public Double getSuperficie();
}
