package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPAS.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IPAS {
	public int getCodigoPersonal();
	
	public int getAñoIncorporacion();
}
