package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPAS.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IPAS {
	public Integer getCodigo_Personal();
	
	public Integer getAño_Incorporacion();
}
