package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPDI.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IPDI {
	public String getCodigoTrabajador();
	
	public String getCategoria();
	
	public String getHorarioTrabajo();
}
