package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPDI.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IPDI {
	public Integer getCodigo_Trabajadorl();
	
	public String getCategoria();
	
	public String getHorario_Trabajol();
}
