package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ISistemaCentral.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//


import java.util.HashMap;

public interface ISistemaCentral {
	public String procesarPeticion(String url, HashMap<String,String> params);
}
