package Interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuario.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//




public interface IUsuario {
	public String getNombre();
	
	public String getPrimerApellido();
	
	public String getSegundoApellido();
	
	public String getCorreo();
	
	public String getContraseña();
	
	public String getDNI();
}
