package Views;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaUsuario.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//

import Controllers.ControladorUsuario;
import Interfaces.IAlumno;
import Interfaces.IPAS;
import Interfaces.IPDI;
import Interfaces.IUsuario;
import Models.Alumno;
import Models.PAS;
import Models.PDI;
import servidor.ObtencionDeRol;

import java.util.HashMap;
import java.util.Scanner;

public class VistaUsuario {
	private ControladorUsuario Controlador;

	public VistaUsuario( ControladorUsuario controladorUsuario) {
		this.Controlador = controladorUsuario;
	}
	
	public void renderAlumno(Alumno alumno) {
		System.out.printf(alumno.toString());
	}
	
	public void renderPDI(PDI pdi) {
		System.out.printf(pdi.toString());
	}
	
	public void renderPAS(PAS pas) {
		System.out.printf(pas.toString());
	}

	public void renderUsuario(IUsuario usuario){

	}
	public void renderNewUsuario(){
		Scanner scanner = new Scanner(System.in);
		HashMap<String,String> datos = new HashMap<>();
		System.out.printf("\nIntroduce tu nombre: ");
		datos.put("nombre",scanner.nextLine());
		System.out.printf("\nIntroduce tu primer apellido: ");
		datos.put("primer apellido",scanner.nextLine());
		System.out.printf("\nIntroduce tu segundo apellido: ");
		datos.put("segundo apellido",scanner.nextLine());
		System.out.printf("\nIntroduce tu correo: ");
		String correo = scanner.nextLine();
		datos.put("correo",correo);
		System.out.printf("\nIntroduce tu constraseña: ");
		datos.put("contraseña",scanner.nextLine());
		System.out.printf("\nIntroduzca su dni: ");
		datos.put("dni",scanner.nextLine());

		Controlador.darAlta(datos);
	}

	public void renderEliminarUsuario(){
		Scanner scanner = new Scanner(System.in);
		System.out.printf("¿Que usuario desea eliminar? Introduce su correo: ");
		String correoTemp = scanner.nextLine();
		Controlador.eliminarUsuario(correoTemp);
	}

	public void renderUpdateUsuario(){
		Scanner scanner = new Scanner(System.in);
		HashMap<String,String> datos = new HashMap<>();
		System.out.printf("\n¿Que usuario desea modificar? Introduzca su correo: ");
		String correo = scanner.nextLine();
		boolean seguir= true;
		while(seguir){
			System.out.printf("¿Que dato desea modificar?: ");
			String dato = scanner.nextLine();
			System.out.printf("¿Que valor nuevo le quiere asignar?: ");
			String valor = scanner.nextLine();
			datos.put(dato,valor);
			System.out.printf("¿Desea cambiar algo mas? (Y/N): ");
			String opcion = scanner.nextLine();
			if(opcion.equals("N")){
				seguir=false;
			}
		}

		Controlador.update(correo,datos);
	}
	public void renderVerUsuario(){
		Scanner scanner = new Scanner(System.in);
		System.out.printf("¿Que usuario desea ver? \nIntroduzca su correo: ");
		String correo = scanner.nextLine();
		Controlador.verUsuario(correo);
	}
	public void renderLogin(){
		Scanner scanner = new Scanner(System.in);
		System.out.printf("Introduce tu correo: ");
		String correo = scanner.nextLine();
		System.out.printf("Introduce tu contraseña: ");
		String pass = scanner.nextLine();

		Controlador.login(correo, pass);
	}
	public void renderError(String error){
		System.out.printf(error);
	}
}
