package Views;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaAula.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//

import Controllers.ControladorAula;
import Interfaces.*;

import java.util.HashMap;


public class VistaAula {
	private ControladorAula ControladorA;
	public VistaAula( ControladorAula controladorA) {
		this.ControladorA = controladorA;
	}
	
	public String renderAula(IAula aula) {
		return null;
	}

	public void renderNewAula(HashMap<String, String > params){

	}
}
