package Views;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaSistema.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//

import System.*;

import java.util.HashMap;
import java.util.Scanner;


public class VistaSistema {
	private SistemaCentral sistemaCentral;
	private Scanner scanner = new Scanner(System.in);
	public VistaSistema(SistemaCentral sistema) {
		sistemaCentral = sistema;
	}

	public String renderPaginaPrincipal() {
		boolean exit = false;

		while(!exit) {
			System.out.println("\n************************************************************" +
					           "\n******************** My UPM Classroom **********************" +
					           "\n************************************************************" +
					           "\nMenu de Acciones: ");
			System.out.print("1.- Anadir usuario.\n2.- Anadir aula.\n3.- Ver Aula.\n4.- Suscribir a un aula.\n0.- EXIT.\n");
			switch (scanner.nextLine()) {
				case "0":
					exit = true;
					break;
				case "1":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users", new HashMap<>());
					break;
				case "2":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas", new HashMap<>());
					break;
				case "3":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/views", new HashMap<>());
					break;
				case "4":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users/aulas/", new HashMap<>());
					break;
				default:
					System.out.println("\nPor favor, seleccione una de las opciones.\n");
			}
		}
		return null;
	}
	
	public String renderPaginaError() {
		return null;
	}
}
