package Views;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaSistema.java
//  @ Date : 28/04/2022
//  @ Author : 
//
//

import System.*;

import java.util.HashMap;
import java.util.Scanner;


public class VistaSistema {
	private SistemaCentral sistemaCentral;
	private Scanner scanner = new Scanner(System.in);
	public VistaSistema(SistemaCentral sistema) {
		sistemaCentral = sistema;
	}

	public String renderPaginaPrincipal() {
		boolean exit = false;

		while(!exit) {
			System.out.println("\n************************************************************" +
					           "\n******************** My UPM Classroom **********************" +
					           "\n************************************************************" +
					           "\nMenu de Acciones: ");
			System.out.print("1.- Anadir usuario.\n2.- Ver un usuario.\n3.- Modificar un usuario." +
					"\n4.- Borrar un usuario.\n5.- Anadir aula.\n6.- Ver Aula.\n7.- Modificar un aula." +
					"\n8.- Borrar un aula.\n9. - Ver todas las aulas" + "\n10. - Suscribirse a un Aula" +
					"\n11. - Desuscribirse de un Aula" +
					"\n0.- EXIT.\n");
			switch (scanner.nextLine()) {
				case "0":
					exit = true;
					break;
				case "1":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users/new");
					break;
				case "2":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users/views");
					break;
				case "3":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users/update");
					break;
				case "4":
					sistemaCentral.procesarPeticion("https://myupmclassroom/users/delete");
					break;
				case "5":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/new");
					break;
				case "6":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/views");
					break;
				case "7":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/update");
					break;
				case "8":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/delete");
					break;
				case "9":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/all");
					break;
				case "10":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/suscribe");
					break;
				case "11":
					sistemaCentral.procesarPeticion("https://myupmclassroom/aulas/unsuscribe");
					break;
				default:
					System.out.println("\nPor favor, seleccione una de las opciones.\n");
			}
		}
		return null;
	}
	
	public String renderPaginaError() {
		return null;
	}
}
